env: "local" # local, dev, prod, etc
database:
  host: "localhost"
  port: 5432
  user: "mak"
  password: ""
  dbname: "urlshortener"
  sslmode: "disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
  